# How to collect some data from uniswap protocol ...

# Explore Uniswap v2 API 

The `Subraph` is based on the graph protocol hosted service and is updated every time a transaction is made. 

[Subgraph Explorer](https://thegraph.com/explorer/subgraph/uniswap/uniswap-v2) (a sandbox where queries can be tested):

Queries are `GraphQL` queries. No aggregations and joins against the api can be performed. 


*   **Section 1** imports required libraries and defines some helper functions. 

*   **Section 2** defines several queries to be used for historical data collection for EDA of Liquidity Pools.
*   **Section 3** perform the ETL - Google Cloud Storage is used for data lake.

https://docs.uniswap.org/sdk/subgraph/subgraph-examples

In [1]:
import datetime

import pandas as pd

In [2]:
from collect import uniswapCollector

In [1]:
collector = uniswapCollector(version=3)

NameError: name 'uniswapCollector' is not defined

In [ ]:
# query pools
pools, errors = collector.execute_many(name='pools', verbose=True)

In [4]:
# select pool_id from **pools**
ticks, errors = collector.execute_many(name='ticks', verbose=True, debug=False, pool_id="0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8")

Status code: 200
Total rows fetched from the query 858

In [5]:
pd.concat(ticks)

,id,tickIdx,price0,price1,liquidityNet,liquidityGross
0,0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8#0,0,1,1,0,0
1,0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8#105960,105960,39953.44719942822385402034558214009,0.00002502912940173810732272813416956387,0,0
2,0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8#-1080,-1080,0.8976324433094195884383843668365469,1.114041729945910239807309095780991,955255939572502,955255939572502
3,0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8#115140,115140,100049.8997864926770132351218727111,0.000009995012510097544967562707071231679,50602192969252,50602192969252
4,0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8#120660,120660,173754.1660171966344141422511922068,0.000005755257689194220169430331041597795,0,0
...,...,...,...,...,...,...
853,0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8#-88...,-887160,0.00000000000000000000000000000000000000297205...,336467360688469975957440017642336300000,98653390708394,98653390708394
854,0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8#887220,887220,338492131855223783697272027725930700000,0.00000000000000000000000000000000000000295427...,-749279610667643,749279610667643
855,0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8#-88...,-887220,0.00000000000000000000000000000000000000295427...,338492131855223783697272027725930700000,775790015893589,775790015893589
856,0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8#92040,92040,9932.225300536398525247462985491484,0.0001006823717486547676557039792075576,0,0
857,0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8#92100,92100,9991.994793093059210757145302033331,0.000100080116203748168163561592702797,1936342093107,1936342093107

In [6]:
# select tick_id from **ticks**
tick_daily_datas, errors = collector.execute_many(name='tickDayDatas', verbose=True, debug=False, tick_id=105960)

Status code: 200
Total rows fetched from the query 122

In [8]:
tick_daily_df = pd.concat(tick_daily_datas)

In [10]:
tick_daily_df.sort_values('date')

,id,date,tick,liquidityNet,liquidityGross,volumeUSD,volumeToken0,volumeToken1,feesUSD
55,0xba8eb224b656681b2b8cce9c3fc920d98594675b#-10...,1620259200,{'price0': '0.00002502912940173810732272813416...,-1976056160463424633026,1976056160463424633026,0,0,0,0
22,0x45f199b8af62ab2847f56d0d2866ea20da0c9bbc#-10...,1620259200,{'price0': '0.00002502912940173810732272813416...,6209798205412485109,6209798205412485109,0,0,0,0
1,0x05a5483f6e5a933c98c9987f81682c90e0133d79#-10...,1620259200,{'price0': '0.00002502912940173810732272813416...,-10616404356585999212,10616404356585999212,0,0,0,0
56,0xba8eb224b656681b2b8cce9c3fc920d98594675b#-10...,1620345600,{'price0': '0.00002502912940173810732272813416...,-3457321436751734357795,3457321436751734357795,0,0,0,0
41,0x98409d8ca9629fbe01ab1b914ebf304175e384c8#105...,1620604800,{'price0': '39953.4471994282238540203455821400...,260149218518171887332,260149218518171887332,0,0,0,0
...,...,...,...,...,...,...,...,...,...
21,0x3eb8224923774f668d6e722cdbf8b0f4e46dae38#-10...,1641254400,{'price0': '0.00002502912940173810732272813416...,-399767169342762450331,399767169342762450331,0,0,0,0
63,0xc2e9f25be6257c210d7adf0d4cd6e3e881ba25f8#-10...,1641427200,{'price0': '0.00002502912940173810732272813416...,2177834741401182516773,2177834741401182516773,0,0,0,0
78,0xe16be1798f860bc1eb0feb64cd67ca00ae9b6e58#105...,1641772800,{'price0': '39953.4471994282238540203455821400...,-227054436051721185049,227054436051721185049,0,0,0,0
36,0x8fec7a391cd9838935f4d4fd516ba6a3b3d2cda7#-10...,1643500800,{'price0': '0.00002502912940173810732272813416...,-518841832919869571904598,518841832919869571904598,0,0,0,0
45,0x98409d8ca9629fbe01ab1b914ebf304175e384c8#105...,1643932800,{'price0': '39953.4471994282238540203455821400...,1482525857356214415127,1482525857356214415127,0,0,0,0

In [13]:
ticks_daily_df2 = pd.concat([tick_daily_df.drop(columns=['tick']), tick_daily_df['tick'].apply(pd.Series).add_suffix('_tick')], axis=1)

In [32]:
ticks_daily_df2.sort_values('date')[['date', 'price0_tick', 'price1_tick']]

,date,price0_tick,price1_tick
55,1620259200,0.00002502912940173810732272813416956387,39953.44719942822385402034558214009
22,1620259200,0.00002502912940173810732272813416956387,39953.44719942822385402034558214009
1,1620259200,0.00002502912940173810732272813416956387,39953.44719942822385402034558214009
56,1620345600,0.00002502912940173810732272813416956387,39953.44719942822385402034558214009
41,1620604800,39953.44719942822385402034558214009,0.00002502912940173810732272813416956387
...,...,...,...
21,1641254400,0.00002502912940173810732272813416956387,39953.44719942822385402034558214009
63,1641427200,0.00002502912940173810732272813416956387,39953.44719942822385402034558214009
78,1641772800,39953.44719942822385402034558214009,0.00002502912940173810732272813416956387
36,1643500800,0.00002502912940173810732272813416956387,39953.44719942822385402034558214009
45,1643932800,39953.44719942822385402034558214009,0.00002502912940173810732272813416956387

In [29]:
ticks_daily_df2.sort_values('date')['price1_tick']

55         39953.44719942822385402034558214009
22         39953.44719942822385402034558214009
1          39953.44719942822385402034558214009
56         39953.44719942822385402034558214009
41    0.00002502912940173810732272813416956387
                        ...
21         39953.44719942822385402034558214009
63         39953.44719942822385402034558214009
78    0.00002502912940173810732272813416956387
36         39953.44719942822385402034558214009
45    0.00002502912940173810732272813416956387
Name: price1_tick, Length: 122, dtype: object

In [18]:
ticks_daily_df2.sort_values('date')['liquidityGross'].plot()

TypeError: no numeric data to plot

In [27]:
ticks_daily_df2['liquidityGross'].astype(float).median()

1.64973195934665e+17

In [6]:
errors

[]

In [ ]:
class uniswapTransformer():

    def __init__(self, version=3):
        self.version = version

    @staticmethod
    def transform_pools(pools):
        """
        """

        pools_df = pd.concat(pools)

        pools_df = pd.concat([pools_df.drop(columns=['token0']), pools_df['token0'].apply(pd.Series).add_suffix('_token0')], axis=1)
        pools_df = pd.concat([pools_df.drop(columns=['token1']), pools_df['token1'].apply(pd.Series).add_suffix('_token1')], axis=1)

        pools_df['dummy'] = 1
        pools_df = self.add_created_date(pools_df)

        return pools_df

    @staticmethod
    def add_created_date(df):
        """
        """

        today = datetime.datetime.today().date()
        df['year']  = today.year
        df['month'] = today.month
        df['day']   = today.day

        return df

In [12]:
pools_df = pd.concat(pools)

In [13]:
pools_df = pd.concat([pools_df.drop(columns=['token0']), pools_df['token0'].apply(pd.Series).add_suffix('_token0')], axis=1)
pools_df = pd.concat([pools_df.drop(columns=['token1']), pools_df['token1'].apply(pd.Series).add_suffix('_token1')], axis=1)

In [24]:
pools_df[(pools_df['symbol_token1']=='WETH') & (pools_df['symbol_token0']=='USDC')]

,id,createdAtTimestamp,feeTier,liquidity,token0Price,token1Price,volumeToken0,volumeToken1,volumeUSD,feesUSD,...,volume_token0,volumeUSD_token0,feesUSD_token0,id_token1,symbol_token1,name_token1,decimals_token1,volume_token1,volumeUSD_token1,feesUSD_token1
797,0x7bea39867e4169dbe237d55c8242a8f2fcdcc387,1620158865,10000,326897210854051059,3004.951215475947815825835081269109,0.0003327841047301701808866536123295881,391731488.189563,116725.059901444461227236,391731365.215478322561512854313954,3917313.65215478322561512854313954,...,237627582081.747883,237636156913.8164571514734193651618,274101910.1652922606278174897218984,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,WETH,Wrapped Ether,18,107885070.361487191590942671,347206659019.685184162613439926366,698828692.9042929824194565085439441
106,0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640,1620250931,500,17310576822744384755,2964.174342555375784617737590503017,0.0003373620726835902401124976921334233,136730726292.938117,42105176.895031425316077624,136749091393.2478782858332868328062,68374545.69662393914291664341639431,...,237627582081.747883,237636156913.8164571514734193651618,274101910.1652922606278174897218984,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,WETH,Wrapped Ether,18,107885070.361487191590942671,347206659019.685184162613439926366,698828692.9042929824194565085439441
147,0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8,1620169800,3000,11866425365361970265,2962.169698679811393390645600043334,0.0003375903819574155309066459446058062,43690227722.561741,15078630.531212591396948278,43693336692.86936052425935256445117,131080010.0786080815727780576933501,...,237627582081.747883,237636156913.8164571514734193651618,274101910.1652922606278174897218984,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,WETH,Wrapped Ether,18,107885070.361487191590942671,347206659019.685184162613439926366,698828692.9042929824194565085439441
32,0xe0554a476a092703abdb3ef35c80e0d76d32939f,1636926269,100,347236890758409,2990.490556123385832645954475206724,0.0003343932981003336779916129125793962,13389451.158215,3461.719657338681504188,13389725.33725297158639323226251825,1338.972533725297158639323226251825,...,237627991978.333883,237636566719.599012074338974677301,274102083.6627454556928200208065679,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,WETH,Wrapped Ether,18,107885465.356104896184499683,347207829217.9511091951826803699847,698831198.1433052169440870281954913